### ISSUE TITLE
如何添加编译参数 -Wl,-subsystem,windows

### ISSUE THREAD

**Issue by leitwolf** [waruqi/xmake#10]
编译GUI程序中，可以在cmake中通过 target_link_libraries(simple xxx -Wl,-subsystem,windows) 来隐藏console窗口。但在xmake 中我试了add_ldflags不行，请问如何才能有效的加上这些参数。

**Comment by waruqi** [comment]
这个参数应该是可以加上的，你可以执行：`xmake -v` 看下实际链接具体的参数列表，确认下是否加上了。

谢谢。

**Comment by leitwolf** [comment]
是加上了，不过还有console窗口。
后来我在程序中加入
`#pragma comment( linker, "/subsystem:\"windows\" /entry:\"mainCRTStartup\"" )`
就可以了。
不知道是不是因为我之前是用mingw编译的，现在是vc++。

**Comment by waruqi** [comment]
那你吧mainCRTStartup也加到ldflags试试呢：

add_ldflags("-Wl,-subsystem,windows", "-Wl,-entry,mainCRTStartup")

**Comment by leitwolf** [comment]
实践证明，不行。

**Comment by waruqi** [comment]
-Wl, 是 mingw下 gcc.exe 传递给链接器的。。在vs上应该直接 用的 `link.exe -subsystem:windows`

所以是可以试下这么写：

`add_ldflags("-subsystem:windows")`

不过这么写，xmake检测这个flag会失败掉，你需要从master上更新下xmake再试试，我修复了下对 这个 flags的检测。。

**Comment by waruqi** [comment]
我这边测试了下。。是ok的

**Comment by leitwolf** [comment]
`add_ldflags("-subsystem:windows")` 并不行。
版本：2.0.2
错误信息：
error: C:\Program Files (x86)\xmake/core/base/os.lua:441: LIBCMT.lib(exe_winmain.obj) : error LNK2019: 无法解析的外部符 号 _WinMain@16，该符号在函数 "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ) 中被引用

**Comment by waruqi** [comment]
报这个错，说明`add_ldflags("-subsystem:windows") `这个已经生效了，只是程序的入口没有改成 WinMain 。。所以出错了。。

因为这个`-subsystem:windows`设置后，默认的入口是WInMain。。

根据你之前的反馈，你这边的程序入口应该还是main吧，可以尝试把 `-entry:mainCRTStartup` 也加上，强制入口从main进入，而不是WinMain

     add_ldflags("-subsystem:windows", "-entry:mainCRTStartup")

**Comment by leitwolf** [comment]
嗯，确实可以了，谢谢啊。
初学者，啥都不懂，呵呵！

**Comment by waruqi** [comment]
不客气
