### ISSUE TITLE
Follow Windows rules for application configs

### ISSUE THREAD

**Issue by ekd123** [waruqi/xmake#12]
On Windows, it's alien to use a dotfile in the home directory (as for xmake, ~/.xmake). A more appropriate place would be %APPDATA%/xmake.

This seems easy to fix. I do hope this will be changed. Thanks!

**Comment by waruqi** [comment]
Hi,

It has been placed into the user applcation data directory: %APPDATA%/.xmake

xmake will translate path: '~' to %APPDATA% automatically. : )

You can write a lua script to verify it.

Write test.lua:

    function main()
        print(path.translate("~/xmake"))
    end

And run it for showing the real path:

    $ xmake lua test.lua

My results:

    C:\Documents and Settings\All Users\Application Data\xmake

Thansk!
