### ISSUE TITLE
请问 如何获取环境变量？

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#13]
我使用
local os = require('os')
print(os.getenv("HOME"))

总是提示
error: /usr/local/Cellar/xmake/2.0.3/share/xmake/core/base/os.lua:457: /Users/bailong/github/long/xmake-cpputest/xmake.lua:7: attempt to call global 'require' (a nil value)
stack traceback:
    [/Users/bailong/github/long/xmake-cpputest/xmake.lua:7]: in main chunk

stack traceback:
	[C]: in function 'error'
	/usr/local/Cellar/xmake/2.0.3/share/xmake/core/base/os.lua:457: in function 'raise'
	...cal/Cellar/xmake/2.0.3/share/xmake/core/project/task.lua:364: in function 'tasks'
	...cal/Cellar/xmake/2.0.3/share/xmake/core/project/task.lua:407: in function 'submenu'
	...ocal/Cellar/xmake/2.0.3/share/xmake/core/base/option.lua:42: in function '_translate'
	...ocal/Cellar/xmake/2.0.3/share/xmake/core/base/option.lua:182: in function 'init'
	/usr/local/Cellar/xmake/2.0.3/share/xmake/core/main.lua:112: in function </usr/local/Cellar/xmake/2.0.3/share/xmake/core/main.lua:103>

**Comment by waruqi** [comment]
为了考虑xmake.lua描述的规范性和安全性，xmake.lua的全局域，我禁用了大部分lua的内置模块，以及对require的私自调用。。

目前仅开发以下接口：`print, pairs, ipairs, format`
以及以下模块：`string, table, path`

因为过多的系统模块操作，会混乱xmake.lua的整体描述风格，并且带来不安全性（尤其是一些写操作、运行接口等等）

不过`os.getenv`这种读取接口，还是可以开放出来，我已经的master版本中更新了，你可以fetch最新版后，试试直接调用（os模块我没开放出来）：

```lua
print(getenv("HOME"))
```

但并不是xmake不能操作这些系统模块，只是操作的作用域受到了一些限制，在自定义的脚本中、插件开发中、task任务的实现中，这些任何由`function() end` 包裹的地方，都是可以使用 os以及一些更强大的扩展模块的。。

例如：

```lua
target("test")
    set_kind("static")
    add_files("src/*.c")

    -- 在构建完成后，执行一些自定义的脚本
    after_build(function()

          -- 这个时候可以使用内置os模块的任何接口，以及一些扩展接口
          print(os.getenv("HOME"))

         -- 运行其他shell（不带回显输出，仅当失败时输出）
         os.run("echo hello")

         -- 运行并且回显输出所有信息
         os.exec("echo hello")
         
         -- 复制文件
         os.cp("/xxx/xxx", "/zzz/zzz")

    end)
```

还有更多的第三方模块，可以通过 `import` 导入后使用，类型`require`，但是更方便了。。

如果了解更多，可以参考：

* [插件开发之import类库](http://tboox.org/cn/2016/06/09/api-import/)
* [高级特性之自定义脚本使用 ](http://tboox.org/cn/2016/06/09/custom-action/)

谢谢。。

**Comment by longbai** [comment]
好吧，昨天想找这个开发指南没在WIKI 中找到，before build 也有hook吧？

**Comment by waruqi** [comment]
也有。。在 [高级特性之自定义脚本使用](http://tboox.org/cn/2016/06/09/custom-action/) 也有描述，这个文档wiki里面也有：[wiki文档](https://github.com/waruqi/xmake/wiki/%E7%9B%AE%E5%BD%95)

下面的on_xxx接口会直接替换内置的实现

- on_build: 自定义构建脚本
- on_clean: 自定义清除脚本
- on_package: 自定义打包脚本
- on_install: 自定义安装脚本
- on_uninstall: 自定义卸载脚本
- on_run: 自定义运行脚本

下面的 before_xxx接口，会在on_xxx之前执行

- before_build: 在构建之前执行一些自定义脚本
- before_clean: 在清除之前执行一些自定义脚本
- before_package: 在打包之前执行一些自定义脚本
- before_install: 在安装之前执行一些自定义脚本
- before_uninstall: 在卸载之前执行一些自定义脚本
- before_run: 在运行之前执行一些自定义脚本

下面的 after_xxx接口，会在on_xxx之后执行

- after_build: 在构建之后执行一些自定义脚本
- after_clean: 在清除之后执行一些自定义脚本
- after_package: 在打包之后执行一些自定义脚本
- after_install: 在安装之后执行一些自定义脚本
- after_uninstall: 在卸载之后执行一些自定义脚本
- after_run: 在运行之后执行一些自定义脚本
