### ISSUE TITLE
main 重复 编译冲突 只是 提示

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#14]
[00%]: compiling.release src/Tutorial/tutorial.cxx
error: /usr/local/Cellar/xmake/2.0.3/share/xmake/core/base/os.lua:457: assertion failed!
stack traceback:
    [C]: in function 'error'
    [/usr/local/Cellar/xmake/2.0.3/share/xmake/core/base/os.lua:457]: in function 'raise'
    [...llar/xmake/2.0.3/share/xmake/core/sandbox/modules/os.lua:363]: in function 'raise'
    [...ake/2.0.3/share/xmake/core/sandbox/modules/coroutine.lua:57]: in function 'resume'
    [...r/xmake/2.0.3/share/xmake/actions/build/kinds/object.lua:251]: in function 'buildall'
    [...r/xmake/2.0.3/share/xmake/actions/build/kinds/binary.lua:32]: in function 'build'
    [...Cellar/xmake/2.0.3/share/xmake/actions/build/builder.lua:35]: in function 'script'
    [...Cellar/xmake/2.0.3/share/xmake/actions/build/builder.lua:53]: in function '_build_target'
    [...Cellar/xmake/2.0.3/share/xmake/actions/build/builder.lua:75]: in function '_build_target_and_deps'
    [...Cellar/xmake/2.0.3/share/xmake/actions/build/builder.lua:144]: in function 'build'
    [...al/Cellar/xmake/2.0.3/share/xmake/actions/build/main.lua:67]:

**Comment by waruqi** [comment]
这个是因为 v2.0.3版本，暂时不支持 `*.cxx` 后缀的c++文件，你可以fetch master版本后再试下，我修复这个问题了。。

谢谢
