### ISSUE TITLE
请问能给个tdd 开发的模版么？

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#15]
我做了个 https://github.com/longbai/xmake-cpputest， 编译总是有问题。如果您能够提供个模版，大家使用会方便许多 👍 
感觉这个工具还是很不错

**Comment by waruqi** [comment]
这个模板暂时没有，如果您有兴趣的话，可以帮忙贡献下，放到`xmake/templates`就行了，模版的扩展，还是很方便的。。：）

谢谢
