### ISSUE TITLE
请问下is_os 和 is_plat 两个API的区别是什么？

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#16]
看起来都一样

**Comment by waruqi** [comment]
你可以看下，xmake的[wiki接口文档](https://github.com/waruqi/xmake/wiki/%E5%B7%A5%E7%A8%8B%E6%8F%8F%E8%BF%B0api%E6%96%87%E6%A1%A3)

里面有相关者两个api的介绍：

[is_os](https://github.com/waruqi/xmake/wiki/is_os)

主要是用于判断，当前编译的程序是在什么os上运行的，例如：windows/mingw编译平台编译出来的，都是 windows的 os系统。

iphoneos/watchos编译平台编译出来的都是 ios系统，等等。。

[is_plat](https://github.com/waruqi/xmake/wiki/is_plat)

主要是用于区分编译平台，也就是：`xmake f --plat=macosx` 配置的参数值
