### ISSUE TITLE
xmake 使用的编译器和环境变量设定的编译器不一致

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#18]
linux 下
 export CXX=clang++
export CC=clang

xmake c
configure
{
    ex = "ar"
,   arch = "x86_64"
,   ccache = "ccache"
,   host = "linux"
,   ld = "g++"
,   mode = "debug"
,   sh = "g++"
,   cc = "gcc"
,   ar = "ar"
,   cxx = "g++"
,   kind = "static"
,   buildir = "build"
,   CppUTest = false
,   as = "gcc"
,   plat = "linux"
}

mac下 设置gcc, 出来的结果是clang

**Comment by waruqi** [comment]
xmake目前检测编译器，不通过环境变量 CC，如果需要手动修改编译器，可以执行：

```bash
$ xmake f --cc=clang --cxx=clang++
```

**Comment by longbai** [comment]
多谢大力支持，不过还是有点问题 见
https://travis-ci.org/longbai/xmake-cpputest/jobs/150988770
使用指定参数时，第一次显示却是系统的，不过存下来倒是对的。 另外我不确定as，sh, ld 是否也应该跟着变化。

**Comment by longbai** [comment]
响应真快，👍。
