### ISSUE TITLE
指定编译器时，显示的和真正配置不一样

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#19]
多谢大力支持，不过还是有点问题 见
https://travis-ci.org/longbai/xmake-cpputest/jobs/150988770
使用指定参数时，第一次显示却是系统的，不过存下来倒是对的。 另外我不确定as，sh, ld 是否也应该跟着变化。

**Comment by waruqi** [comment]
这个问题我后两天看下 电脑最近坏了 暂时没法敲代码了 。。 ld这些不会随着变动的

**Comment by waruqi** [comment]
我看了下，第一次指定cc为clang后，xmake -v 编译已经是clang了，没问题。。那个`checking for the assember (as) ... gcc` 的显示，也是对的，因为不会影响到 as ld 这些

`xmake f --cc=clang`指定后，`checking for cc ` 的显示久没有了，因为手动指定后，就不去check了，只要看到 configure的结果 cc已经生效，那之后的编译肯定用的是clang。。

是ok的，谢谢。

**Comment by waruqi** [comment]
还有 在 linux 和 macosx下，如果是非交叉编译的情况下，我已经加上对  $CC $CXX $AR $LD 这个环境变量的检测支持，优先会使用这里面的值，除非手动配置修改：`xmake f --cc=clang`

**Comment by longbai** [comment]
测试OK了
