### ISSUE TITLE
win7 X64 install无法生成

### ISSUE THREAD

**Issue by cnicjie** [waruqi/xmake#2]
compile.r os/rmfile.c
compile.r os/setenv.c
compile.r os/strerror.c
compile.r os/tmpdir.c
compile.r path/absolute.c
compile.r path/is_absolute.c
compile.r path/relative.c
compile.r path/translate.c
compile.r string/endswith.c
compile.r string/startswith.c
compile.r xmake.c
link xmaker.lib
make ../demo
compile.r xmake.c
link demo.exe
make.exe[1]: Leaving directory `/k/third_party/xmake-master/core'
make.exe[1]: Entering directory `/k/third_party/xmake-master/core'
install xmake
make xmake
make ../demo
make.exe[4]: Nothing to be done for `all'.
install xmake
install ../demo
make.exe[1]: Leaving directory `/k/third_party/xmake-master/core'

**Comment by waruqi** [comment]
已修复，请clone最新master版本试下。。
