### ISSUE TITLE
如何让 xmake 在检测环境时执行自定义命令？

### ISSUE THREAD

**Issue by lc-soft** [waruqi/xmake#20]
比如在检测时执行 git clone 命令，下载依赖库的源码（依赖库源码中没有makefile），然后将它的源文件引入当前的源文件构建清单中。

**Comment by waruqi** [comment]
我下个大版本，会实现依赖包的自动下载和编译，来直接进行支持，不过最近时间不够，可能还需要等上些时间。。

现在的版本，可以通过在build构建任务之前，插入自动定义脚本，来解决这个问题：

```lua
target("test")
    set_kind("binary")
    
    -- 在build编译任务之前，执行脚本
    before_build(function ()
        os.exec("git clone repo")
        os.cd("repo")
        os.exec("xmake")
    end)
```

试试，这个任务是在自动检测之后、编译任务之前执行的。。

更多类库和api使用介绍，请参考：[xmake插件开发之类库使用](http://tboox.org/cn/2016/07/07/plugin-modules/)

除了before_build，更多自定义脚本阶段，请参考：[高级特性之自定义脚本使用](http://tboox.org/cn/2016/06/09/custom-action/)

谢谢！

**Comment by lc-soft** [comment]
原来是用 os.exec()，我之前用 os.execute() 发现这个函数不存在，以为是 xmake 的问题。

**Comment by waruqi** [comment]
xmake的自定义脚本中，为了保证语法的简洁性，简化脚本开发，提升脚本安全性，因此设置了独立的作用域，并且重新封装了一些api，以及扩展了一些内建api。。

像os.execute太过原始，写法上比较繁琐，因此xmake里面被禁用了，可以用以下几个api来替代：

```lua

-- 执行shell脚本，如果执行失败，直接中断xmake，并且会实时显示shell的回显输出信息。。
-- 相当于os.execute，但是比os.execute 少了个返回值判断，直接采用异常中断的方式。。
os.exec("git clone ...")

-- 跟os.exec类型，但是执行过程中，不会输出任何信息（安静执行），除非执行失败，才会抛出异常中断xmake, 并且打印失败信息
os.run("git clone ...")

-- 执行shell，并且捕获stderr,stdout的输出数据，如果执行失败，直接中断，并且跑出错误信息
local out, err = os.iorun("git clone ...")
```

`os.exec`相当于:

```lua
local ret = os.execute("git clone ... 2> errors.log")
if ret ~= 0 then
    os.execute("cat errors.log")
    os.exit()
end
```
