### ISSUE TITLE
编译过程中的警告只有在出现错误的时候才一起输出

### ISSUE THREAD

**Issue by lc-soft** [waruqi/xmake#22]
按理来说，编译过程中如果编译器有输出警告会直接显示才对，但实际运行 xmake 时，这个编译警告只有在编译报错时才一起显示出来，有什么办法可以让编译器警告信息即时显示出来？

话说，错误信息全是红色的看起来不顺眼，有办法取消红色吗？

**Comment by waruqi** [comment]
主要是考虑到实时显示的，如果警告信息过多的，刷屏太厉害，反而看不到实际编译进度，而且影响编译速度和美观

如果确实有这需要的话，我之后可以把实时警告通过：`-v/--verbose`参数，来启用，默认还是无回显编译，这样编译速度也会更快些。。

错误红色高亮，也是为了能够更加一目了然的看到错误信息，跟其他输出给区分开来，暂时不考虑取消，如果个人觉得不是很顺眼的话，可以自己修改下xmake的脚本：`./xmake/core/base/utils.lua `

```
-- the error function
function utils.error(format, ...)

    -- trace
    if format ~= nil then
        utils.cprint("${bright red}error: ${default red}" .. string.tryformat(format, ...))
    end
end
```

把 `${bright red}  ${default red}`删掉就好，你可以直接修改安装好的xmake中的lua脚本。。

**Comment by waruqi** [comment]
色彩高亮，以后可以做成全局配置，自行配置修改，之后的版本，我可以考虑做进去，这样可以根据个人喜好，禁用或者修改各种显示模式的色彩。。

**Comment by lc-soft** [comment]
@waruqi 问题是但警告和错误信息混在一起后，一大片红色不容易找到错误信息。

**Comment by waruqi** [comment]
这个之后可以改成，出错后默认只报error信息，warning信息只在加上`-v/--verbose`编译后，才一起报出来，并且warning信息用黄色显示。。。区分下。。这个确实之前没考虑到。。

**Comment by lc-soft** [comment]
其实只需要为 `error:`  和  `warning:` 这两个字加上颜色就够了，况且，如果编译器用 clang 的话，clang 编译器输出的警告和错误信息会自动加颜色的。

**Comment by waruqi** [comment]
这个还是看个人喜好哈，你可以先自己改下xmake的lua脚本，在之前给的那个位置。

clang只有实时回显才会有颜色。xmake是需要重定向捕获输出的。。没法获取clang的颜色。。

**Comment by waruqi** [comment]
我现在是 `error:`  是加了 高亮红， 信息内容是正常红色，也是有区分的。。

**Comment by waruqi** [comment]
这个提示信息 我做了些改进。。目前的规则如下：

1. 默认安静编译，出错后，仅高亮黄显示最近8行warnings，高亮红显示errors，避免warnings太多，导致满屏全红

2. 加上`-v`参数编译，不仅会显示所有编译参数，还会高亮显示每个源文件编译的warnings（每个8行）

最后，非常感谢您对xmake的支持哈。：）
