### ISSUE TITLE
关于工程依赖的问题

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#25]
我大致看了一下文档,好像工程依赖,是打包供其它工程调用.
如果我的一个项目有多个工程,多个工程里会有依赖,那要是改动了基础模块,
要看效果,不是要先编译打包基础模块,然后再编译,
不知道xmake是否支持子工程,就是工程1依赖工程2,我改动了工程2,只需要xmake一下工程1,
它会自动编译打包工程2酱紫

**Comment by waruqi** [comment]
你好

    子工程和工程依赖是支持的，每个target对应一个子工程，每个target之间可以通过 `add_deps()` 来添加依赖关系，例如：

```lua

-- 主工程
target("main")
    set_kind("binary")
    add_files("src/*.c")
 
    -- 添加对subA子工程的依赖
    add_deps("subA")

-- 子工程
target("subA")
    set_kind("static")
    add_files("src2/*.c")
```

上面的例子就是 主工程main 依赖 子工程 subA，默认编译，执行：`xmake`， 会去编译所有工程，当然优先编译依赖的subA，再去编译main。

也只可以指定编译 main工程：`xmake -r main` ，xmake检测到 main 依赖了 subA，会先去自动编译subA后，再去编译main。。

另外，·add_deps·是可以添加多个工程依赖的，例如：`add_deps("subA", "subB", "subC")`

不仅是编译， 像 打包、运行、安装、卸载、清理等等，各种action和插件任务都是完全支持工程依赖的。。

谢谢

**Comment by baisai** [comment]
谢谢解惑
不错的项目构建工具
正被cmake的交叉编译虐得死去活来,就换这个了....简单明了
有什么不明白的地方就打扰了

**Comment by waruqi** [comment]
感谢您的支持，有问题和bug欢迎提交issues。

：）
