### ISSUE TITLE
xcode 升级到 8 时 出现 找不到sdk

### ISSUE THREAD

**Issue by longbai** [waruqi/xmake#27]
configure ok!
[00%]: compiling.release source/base/binary.c
[03%]: compiling.release source/base/bytebuffer.c
[06%]: compiling.release source/base/string.c
[09%]: compiling.release source/base/tcp.c
error: clang: error: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk'

 ✘  ~●  ls -l  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
total 8
drwxr-xr-x  5 root  wheel  170 Mar  5  2018 MacOSX.sdk
lrwxr-xr-x  1 root  wheel   10 Sep 14 20:25 MacOSX10.12.sdk -> MacOSX.sdk

**Comment by longbai** [comment]
问题找到了，是 .xmake 目录下 xmake.conf 缓存了 sdk 版本，建议不要缓存这个。 sdk 目录可以直接通过MacOSX.sdk

**Comment by waruqi** [comment]
系统环境升级，需要 `xmake f -c` 清下缓存重新检测配置就好。。缓存是为了避免每次都要重新检测，很多其他action都需要获取缓存后的配置，不然每次都去检测一边，太费时间。。特别多个action依赖执行的时候。。
