### ISSUE TITLE
指定工程文件构建的问题

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#30]
C:\Users\Administrator\Desktop\temp>xmake -F testxmake/xmake.lua
error: null

C:\Users\Administrator\Desktop\temp>cd testxmake

C:\Users\Administrator\Desktop\temp\testxmake>xmake -F xmake.lua
configure ok!

C:\Users\Administrator\Desktop\temp>xmake -F testxmake/sharedtest/xmake.lua
configure ok!

testxmake/xmake.lua内容是:
add_subdirs("sharedtest")

还有一个问题,是我在编写多个工程的时候老是遇到目录的问题,因为我用add_subdirs添加了多个目录,加上我是把源码和工程文件分开的,所以更容易遇到目录的问题
不知道有没有办法指定构建的根目录呢

**Comment by waruqi** [comment]
通过 -F 仅仅只是指定工程文件xmake.lua的路径，工程目录还是当前路径，所以构建还是基于当前目录的，主要就是用于工程目录和工程文件xmake.lua分开存储的。。

你可以指定 xmake -P xxxx/projectdir 指定工程目录。。不指定的话，默认一当前目录作为工程目录。。

**Comment by waruqi** [comment]
不过如果指定了-P的话，-F指定的xmake.lua路径是相对于 -P 中的projectdir，这样不用重复指定绝对路径

例如：

`test/console_c/xmake.lua `

在这么指定：

`xmake -P test/console_c -F xmake.lua`

或者：

`xmake -P test -F console_c/xmake.lua`

**Comment by baisai** [comment]
C:\Users\Administrator\Desktop\temp>xmake -P testxmake -F xmake.lua
error: null

我指定了工程目录,还是会报这个错.
但我cd到testxmake 这个目录
xmake就没有问题,不知道什么原因

**Comment by baisai** [comment]
请问有办法拿到当前工程文件的目录么,就是相对于-P指定的目录
也就是一个项目如果有多个工程文件,在各自工程文件里拿到自己所在的目录

**Comment by waruqi** [comment]
各自的工程文件里，使用相对路径，就是基于当前xmake.lua所在的脚本目录的。。

在自定义的脚本里面，例如：on_run 、on_install这种脚本里面，可以使用`os.scriptdir()` 来获取当前的xmake.lua所在目录

**Comment by baisai** [comment]
请问工程文件之前可以共享....或者说传递数据么

**Comment by waruqi** [comment]
定义的变量，如果不加local就是全局共享的，不过只能 子xmake.lua 访问 父xmake.lua定义的变量，反之不行，例如：

根目录xmake.lua

```lua

var1 = 1
var2 = "a"
local var3 = 0

add_subdirs("src")
```

在`src/xmake.lua` 就可以访问这个变量：

```lua

-- 访问全局变量var1, var2
print("%d %s", var1, var2)

-- 无法访问var3，var3只对根xmake.lua的作用域有效，属于局部变量
```

但是返过来，`src/xmake.lua`中定义的变量，根xmake.lua里面是访问不到的

**Comment by baisai** [comment]
谢谢解惑
