### ISSUE TITLE
关于option

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#31]
[高级特性之自定义选项](https://github.com/waruqi/xmake/wiki/%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7%E4%B9%8B%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)
这里关于option的文档貌似有点问题.....
option函数应该和add_option函数同样的效果用来定义option
要绑定option应该是用set_options吧...

**Comment by waruqi** [comment]
add_option是1.x版本的接口，由于命名上有歧义，已在2.x上废弃使用，虽然依旧能够兼容使用，但是调用add_option后，xmake运行完会有deprecated的提示，建议尽量使用新接口option来定义选项。

* option: 定义选项
* add_options: 为target添加绑定选项
* is_option: 判断选项是否启用

因为option被设计可以重入，来增加修改设置， 例如：

```lua

--- 定义选项aaa
option("aaa")
    add_links("xxx")

-- 一些target设置
target("bbb")
....

-- 重新进入aaa选项域，增加宏定义
option("aaa")
   add_defines("yyy")
```

如果用老版本的add_option来定义的，重新修改option再用add_option，在命名上会有歧义。。所以不用了。。

还有add_target这种，也是老版本的废弃接口，建议别去调用。。

**Comment by waruqi** [comment]
文档可能更新上，有些名字忘记更新了，我更新下文档。非常抱歉

**Comment by waruqi** [comment]
文档已更新：[高级特性之自定义选项](https://github.com/waruqi/xmake/wiki/%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7%E4%B9%8B%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)

**Comment by baisai** [comment]
建议,老版本的直接废弃掉,不做兼容,
然后给一个迁移文档,标注一下,发生改变的接口
两个版本在一起,很容易发生误用

**Comment by waruqi** [comment]
如果直接废弃，对原有用户使用老版本api编写xmake.lua工程，就没法编译通过，这样不友好。。

现在的方式是，用户编译老版本的工程，还是可以编译通过，但是编译完成，会有警告提示，哪些api已被废弃，建议使用新版本的Api，这些都有提示的。。

然后等过几个版本迭代后，才会陆陆续续将已有的老api逐步废弃移除，这样过度对原有的老工程比较友好。。。

之前你这边混用问题，主要还是文档更新不及时，以及局部更新导致的问题，后续api升级后，我文档会尽量同步更新。。

**Comment by baisai** [comment]
嗯,好吧...关于文档方面...
可否在[工程描述api文档](https://github.com/waruqi/xmake/wiki/%E5%B7%A5%E7%A8%8B%E6%8F%8F%E8%BF%B0api%E6%96%87%E6%A1%A3)这里的api后面加上一句概要描述呢...
哈哈哈,我记性太好,每次都要点进去看一下...如果加一句概要描述的话,一看就能明白了,比如
set_project  -- 设置工程名
像这样,一眼就能知道了

**Comment by waruqi** [comment]
好的，我有时间抽空加一下。。

**Comment by waruqi** [comment]
已添加，[工程描述api文档](https://github.com/waruqi/xmake/wiki/%E5%B7%A5%E7%A8%8B%E6%8F%8F%E8%BF%B0api%E6%96%87%E6%A1%A3)
