### ISSUE TITLE
找不到add_headers

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#32]
attempt to call global 'add_headers' (a nil value)

**Comment by baisai** [comment]
好吧,我的问题....我用了set_option来绑定option就报这个错了...
改成set_options就可以了...不知道set_option这个接口是干嘛的

**Comment by waruqi** [comment]
set_option 是废弃接口，建议别去用它，绑定选项到 target用的是 add_options或者set_options

其中 add_options 是追加选项绑定，而 set_options 会去覆盖原有的选项绑定，重置后重新绑定新设置的选项。。
