### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#36]
[00%]: compiling.debug ..\..\src\ThirdParty\SDL\SDL.c
[07%]: compiling.debug ..\..\src\ThirdParty\SDL\SDL_assert_c.h
error: assertion failed!

这个错误不知道是什么引起的....没有更多的信息

**Comment by waruqi** [comment]
加-v --backtrace 参数编译看下

**Comment by baisai** [comment]
error: d:\xmake/core/base/os.lua:457: d:\xmake/core/base/os.lua:457: d:\xmake/core/tool/compiler.lua:266: assertion failed!
stack traceback:
	[C]: in function 'assert'
	d:\xmake/core/tool/compiler.lua:266: in function 'load'
	D:\xmake\core\sandbox\modules\import\core\tool\compiler.lua:35: in function 'compcmd'
	D:\xmake\actions\build\kinds\object.lua:164: in function '_build'
	D:\xmake\actions\build\kinds\object.lua:246: in function <D:\xmake\actions\build\kinds\object.lua:240>
stack traceback:
    [C]: in function 'error'
    [d:\xmake/core/base/os.lua:457]: in function 'raise'
    [d:\xmake/core/sandbox/modules/os.lua:377]: in function 'raise'
    [D:\xmake\core\sandbox\modules\coroutine.lua:57]: in function 'resume'
    [D:\xmake\actions\build\kinds\object.lua:251]: in function 'buildall'
    [D:\xmake\actions\build\kinds\shared.lua:32]: in function 'build'
    [D:\xmake\actions\build\builder.lua:35]: in function 'script'
    [D:\xmake\actions\build\builder.lua:53]: in function '_build_target'
    [D:\xmake\actions\build\builder.lua:75]: in function '_build_target_and_deps'
    [D:\xmake\actions\build\builder.lua:144]: in function 'build'
    [D:\xmake\actions\build\main.lua:67]:

stack traceback:
    [C]: in function 'error'
    [d:\xmake/core/base/os.lua:457]: in function 'raise'
    [d:\xmake/core/sandbox/modules/os.lua:377]: in function 'raise'
    [D:\xmake\actions\build\main.lua:77]: in function 'catch'
    [D:\xmake\core\sandbox\modules\try.lua:105]: in function 'try'
    [D:\xmake\actions\build\main.lua:63]: in function 'main'
    [d:\xmake/core/sandbox/sandbox.lua:179]:
    [C]: in function 'load'
    [d:\xmake/core/project/task.lua:416]: in function 'run'
    [d:\xmake/core/main.lua:125]:

**Comment by waruqi** [comment]
compiling.debug ....\src\ThirdParty\SDL\SDL_assert_c.h 

.h 的头文件暂时无法编译，最好别放到add_files()里面去，错误提示信息，我之后再完善下。。

**Comment by baisai** [comment]
好的,谢谢
