### ISSUE TITLE
关于set_languages

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#37]
刚刚碰到一个坑.....
因为要使用到一个库,C编写的,标准是c99,使用了诸如inline之类的
所以我设置了set_languages("c99"),然后一直链接错误,找不到符号....
翻了一下文档...才发现....
"windows下vs的编译器并不支持按c99的标准来编译c代码，只能支持到c89，但是xmake为了尽可能的支持它，所以在设置c99的标准后，xmake会强制按c++代码模式去编译c代码，从一定程度上解决了windows下编译c99的c代码问题"

然后因为是C库,所以有一个#ifdef __cplusplus   extern "C"来检测C++的链接
这样问题就来了....因为使用的C++代码模式,所以导致导出的符号和期望的符号不一致,导致链接错误
去掉extern "C",就没有问题了

我觉得这种情况.....还是应该给一下警告信息........这样排查问题.....方便一些

**Comment by waruqi** [comment]
想我的tbox里面，windows上c++模式编译，所有的接口都是extern "C" 导出的。。强制以c接口方式导出，这样应该是能够正常链接的。。而且更加统一。。在c/c++里面调用都是能够正常链接。。

我不明白为什么你这去掉 extern "C" 反而ok。。

**Comment by waruqi** [comment]
默认不加 extern "C" ，在c++中编译，反而是以c++的命名规则导出接口的。。

**Comment by baisai** [comment]
嗯...因为C库的头文件里并没有extern "C",而是提供了一个C++的头文件lua.hpp这个头文件里有extern "C",所以导致了,C库的接口导出为C++模式的,而C++包含了lua.hpp,期望的是C模式的...所以我去掉了lua.hpp里的extern "C",这样所有的都是C++模式,所以就没有问题了....

当然,也可以把所有的C库的头文件加上#ifdef __cplusplus extern "C"......不过文件太多,所以我选择了更简单快捷的方法啦

**Comment by waruqi** [comment]
了解了 将c自动做为c++编译时 我之后可以考虑加些提示信息

**Comment by baisai** [comment]
好的
