### ISSUE TITLE
Please consider a new API get_objectname

### ISSUE THREAD

**Issue by avaicode** [waruqi/xmake#39]
Last time I created the pull request,but I got an unpassed test with the first commit by travis because of the test `merge_object`.
xmake.lua of this project uses following way to add the built object file into a new target:
` add_files("build/.objs/merge_object/src/interface.c.o")`
I think it's dangerous and it will make building across different versions of xmake incompatible.And common users don't know it unless they look into `build` folder.
My thought:Add a new API `get_objectname`.It receives two arguments,`target` and `source file`.For above example,this statement should be replaced with:
`add_files(getobjectname("merge_object","interface.c"))`
I hope to have a discussion to make it easier to use ;) .

**Comment by waruqi** [comment]
This is a very good suggestion, I will consider adding a simular api in future.

Thanks. : )

**Comment by avaicode** [comment]
Very looking foward to it :smiley:
