### ISSUE TITLE
add_subdirs作用域的问题

### ISSUE THREAD

**Issue by baisai** [waruqi/xmake#40]
在add_subdirs的子工程文件里.....如果没有target,只是add_files..
.这样好像add_files添加的文件,好像因为add_subdirs是全局作用域的原因....会加到所有的target里去...

有没有是target作用域引入子工程,或者子文件,类似require,只单纯包含文件的接口或方法

**Comment by waruqi** [comment]
在自定义脚本中（也就是内层作用域） 是可以通过 import 导入 当前目录或者指定位置的 模块接口。。

外层全局set_xx, add_xx设置的属性会影响后面的所有targets，add_subdirs仅仅只是导入新的xmake.lua文件

而add_files本身就是给target设计的，给指定target添加编译文件，一般不建议在target外面使用。。

如果你想在子xmake.lua 继续给之前的target添加源文件，只需要重新进入target作用域就行了，例如：

```lua
target("test")
    add_files("*.c")

add_subdirs("subdir")
```

subdir中的子工程文件：

```lua

-- 重新进入 test 目标作用域
target("test")

    -- 继续添加其他源文件
    add_files("src/*.c")
```

**Comment by baisai** [comment]
好的,谢谢
另外建议,在文档里专门用一章解释一下,作用域的问题,
我是测试了很多少次,才明白一点是怎么回事

**Comment by waruqi** [comment]
好的 有空我完善下文档 。: )

**Comment by waruqi** [comment]
针对作用域，我写了篇文档，可以参考下：http://tboox.org/cn/2016/10/26/api-scope/

wiki 文档里，也放进去了。。

**Comment by baisai** [comment]
好的,谢谢,写得很详细
