### ISSUE TITLE
关于add_defines和add_defines_if_ok的区别

### ISSUE THREAD

**Issue by xiren7** [waruqi/xmake#42]
在option里面使用这个两个命令, 我感觉这两个命令是等效的.

从代码上好像也是等效的? 是在core/tool/compiler.lua的中的_addflags_from_target函数中执行的?

1.如果这两个命令真的是等效的, 是否只保留一个就行了? 同理add_undefines和add_undefines_if_ok也应该是一样的?

2.另外关于add_defines_h_if_ok, 这个命令是在头文件里面定义宏, 然后你在include这个头文件. 那为什么不直接用add_defines定义了, 最后的结果不是一样的吗? 不太明白为什么要生成这个头文件的必要.

**Comment by waruqi** [comment]
稍微有点区别，option如果在不进行检测，仅仅用于手动配置的情况下，这两个效果都是一样的，就是

```
如果option启用，那么添加宏定义
```

但是在option用于自动检测的情况下，这两个是有区别的

* add_defines：option中所有不带_if_ok的设置，都是在option检测前就设置的，此处用于在检测前添加宏定义
* add_defines_if_ok：_if_ok结尾的表示，在option检测通过后，需要添加的配置，此处用于option检测通过后，添加宏定义

例如：

```lua
option("pcre2")
    
    -- 如果检测通过，会在config.h中添加此此宏开关定义     
    add_defines_h_if_ok("$(prefix)_PACKAGE_HAVE_PCRE2")

    -- 在检测前预先添加PCRE2_CODE_UNIT_WIDTH=8的宏定义，否则编译检测是通不过的
    -- 检测通过后，也会追加此宏定义
    add_defines("PCRE2_CODE_UNIT_WIDTH=8")

    -- 而此宏定义，只会在检测通过后添加，当然手动配置启用，或者默认启用的时候，也会添加此设置
    add_defines_if_ok("XXXX")

    -- 在检测前，添加libpcre-8.a的链接库，检测的时候会去尝试链接它，链接不通过，选项检测失败
    -- 检测通过后，add_options("pcre2") 到target的时候，也会自动追加此链接
    add_links("pcre2-8")

    -- 检测pcre2/pcre2.h的pcre2_compile接口
    add_cincludes("pcre2/pcre2.h")
    add_cfuncs("pcre2_compile")
```

总而言之，option里面不带if_ok的add_xxx接口，检测前设置，检测成功后也会设置
而带if_ok的add_xxx接口，仅在检测成功（或者手动启用，默认启用）后被设置

具体可以参考这篇文章：[http://tboox.org/cn/2016/08/07/custom-option/](http://tboox.org/cn/2016/08/07/custom-option/)

而add_defines_h_if_ok用于在config.h中添加宏定义，一般用于代码中进行条件编译使用

具体config.h的设置，见[set_config_h](https://github.com/waruqi/xmake/wiki/set_config_h)

**Comment by xiren7** [comment]
明白了, 感谢!
