### ISSUE TITLE
能否在mac下生成so文件

### ISSUE THREAD

**Issue by zhangshiqian1214** [waruqi/xmake#44]
我需要在mac下生成一个动态库 手打的命令是这样子的:
gcc -g -O2 -Wall -fPIC -dynamiclib -Wl,-undefined,dynamic_lookup -I../src lsproto.c sproto.c -o sproto.so -L../build
生成出来的文件是:
sproto.so sproto.so.dSYM

但目前用xmake生成出来的是: libsproto.dylib

**Comment by waruqi** [comment]
mac下动态库后缀名默认就是dylib，你只需要重命名成.so就行了 一样的 就是后缀名的区别，如果非要生成 so 后缀 只需要写个自定义脚本，在编译后重命名下
```
after_build(function(target)
    os.mv(target:targetfile(), (target:targetfile():gsub('%.dylib','%.so')))
end)
```

**Comment by zhangshiqian1214** [comment]
我试试,谢谢解答
