### ISSUE TITLE
可以运行xmake命令，但是编译tbox提示如下问题：

### ISSUE THREAD

**Issue by 1197636889** [waruqi/xmake#5]
E:\src-from-net\cross-platform\tbox>xmake
compiling.release src\tbox\tbox.c
'xmake' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
NMAKE : fatal error U1077: “xmake”: 返回代码“0x1”
Stop.

**Comment by 1197636889** [comment]
环境
win x64
vs 2015

**Comment by waruqi** [comment]
windows版本多少？ win8? win10？

**Comment by waruqi** [comment]
windows版本多少？ win8? win10？

**Comment by 1197636889** [comment]
win7

**Comment by waruqi** [comment]
你这边重新up下master上的 tbox和xmake试试呢。。稍微改了下，我这边测下来  win7+vs2015是ok的。。

**Comment by waruqi** [comment]
已修复。。请重新clone master安装下 试试。。

谢谢！
