### ISSUE TITLE
路径反斜杠问题

### ISSUE THREAD

**Issue by zgww** [waruqi/xmake#6]
在mingw和cmd下，生成出来的makefile的路径分隔符是反斜杠。

`@gcc -c -fvisibility=hidden -O3 -m32 -o build\.objs\xm\src\main.o src\main.c > build\.build.log 2>&1`

makefile中SHELL，使用的是mingw/msys 下的sh.exe.
sh.exe不支持路径分隔符为反斜杠，导致编译失败

**Comment by waruqi** [comment]
如果是在windows上编译，那就不需要mingw了。。直接在cmd里面就可以编译，如果装了vs的话。。

如果必须要在windows上的msys里面使用mingw编译，可以尝试clone dev分支的版本，dev分支我重构了大部分代码，是2.0的新版本，已经移除了对makefile的依赖，直接编译的，应该不存在反斜杠不支持的问题，编译速度也有很大提升。。

**Comment by waruqi** [comment]
你这边是直接使用xmake编译的吗，直接用xmake编译的话，调用的是nmake.exe来处理makefile的，应该也不存在反斜杠问题：

直接执行xmake就行了。

不要config完用msys里面的make进行编译
