### ISSUE TITLE
Support clang with c++11?

### ISSUE THREAD

**Issue by avaicode** [waruqi/xmake#9]
I tried clang to build my project. which uses some c++11 futures. 
Command is like this:`xmake f --cc="clang" --cxx="clang++"`
But I failed,I looked through the verbose log and found the c++11 flag was disabled and it gave following reasons.
`error: invalid argument '-std=c++11' not allowed with 'C/ObjC'`
But I am sure that the current file is a cpp source.
So,does xmake support clang with c++11?

**Comment by waruqi** [comment]
I have fixed this problem, please attempt to fetch the last commit again!

: )
